version: "3.7"

services:
  timescaledb:
    build:
      context: build/timescaledb
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"

  app:
    image: docker.pkg.github.com/honzatrtik/hydro/app:${APP_IMAGE_TAG}
    environment:
      DOOBIE_DRIVER: org.postgresql.Driver
      DOOBIE_URL: jdbc:postgresql://timescaledb/hydro
      DOOBIE_USER: $DOOBIE_USER
      DOOBIE_PASSWORD: $DOOBIE_PASSWORD
      MQTT_CLIENT_ID: hydro_client
      MQTT_USERNAME: $MQTT_USERNAME
      MQTT_PASSWORD: $MQTT_PASSWORD
      MQTT_BROKER_URI: tcp://vernemq
    depends_on:
      - timescaledb
      - vernemq
    networks:
      - backend
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"

  grafana:
    image: grafana/grafana:6.7.2
    ports:
      - 80:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: $GF_SECURITY_ADMIN_PASSWORD
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - timescaledb
    networks:
      - backend
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"

  vernemq:
    image: vernemq/vernemq
    ports:
      - 1883:1883
      - 8080:8080
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_VERNEMQ_PLUGINS__VMQ_ACL: "off"
      DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY: "on"
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__HOST: "timescaledb"
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PORT: "5432"
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__USER: $POSTGRES_USER
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PASSWORD: $POSTGRES_PASSWORD
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__DATABASE: "hydro"
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__HASH_METHOD: "crypt"
    networks:
      - backend
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"

volumes:
  db-data:
    driver: local
  grafana-data:
    driver: local
  loki-data:
    driver: local

networks:
  backend: